### ISSUE TITLE
версия GULP

### ISSUE THREAD

**Issue by ArslanMustafin** [brainmurder/InSales-uploader-gulp-test#6]
При команде gulp default возникает ошибка:
``` 
ReferenceError: primordials is not defined
    at fs.js:40:5
    at req_ (D:\projects\insales\inSalesl\node_modules\natives\index.js:143:24)
    at Object.req [as require] (D:\projects\insales\inSalesl\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (D:\projects\insales\inSalesl\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
```
Могу предположить что проблема связана с версией gulp, и нынешней версии node.js

**Comment by AlinaLedova** [comment]
Такая же проблема. Давно не обновлялся uploader. При установке предупреждает, что все устанавливаемые пакеты устарели. Некоторые скипает как не поддерживаемые версией ноды.
